### ISSUE TITLE
Add script to correct SNR map with B1+ map

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#1]

**Comment by evaalonsoortiz** [comment]
@dpapp86 From our discussions today, it sounds like this is no longer needed? If so, I will close this issue.

**Comment by jcohenadad** [comment]
Why is that no longer needed? I suggest to document the reason directly in this issue, just for the records (and we will need to discuss this in the manuscript anyway, so better to all be on the same page)

**Comment by evaalonsoortiz** [comment]
To unify the discussion: https://github.com/spinal-cord-7t/coil-qc-code/issues/2#issuecomment-1839824442

**Comment by jcohenadad** [comment]
Addressed in https://github.com/spinal-cord-7t/coil-qc-code/issues/88
