### ISSUE TITLE
Remove redundant plots

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#103]
This plot:

![download](https://github.com/user-attachments/assets/f38d4a9b-0b20-4bf9-9d47-95cb5a40a72c)

is included in this figure:

![download-1](https://github.com/user-attachments/assets/f75c86bb-f577-4aaf-88b1-c14dc0007415)

Hence, the code pertaining to the first plot can be removed to make the code smaller and less redundant.

Do it for the phantom and for the human notebook.

**Comment by evaalonsoortiz** [comment]
I agree that this can be cleaned up once we've finished creating the figures, but for the time being I'm still using it to debug.

**Comment by jcohenadad** [comment]
> I agree that this can be cleaned up once we've finished creating the figures, but for the time being I'm still using it to debug.

OK, I've already removed it for the phantom notebook ([453b888](https://github.com/spinal-cord-7t/coil-qc-code/commit/453b88897fa66d5c8e902fbe24ab20026aed7b4a)) but I'll wait for the debugging to end before doing it also in the human notebook

**Comment by evaalonsoortiz** [comment]
We only have this type of plot in the phantom notebook, since in the human one, the plots are in a figure that is separate from the tiled maps. It's fine though, I'll make do without.

**Comment by jcohenadad** [comment]
We can close this issue then
