### ISSUE TITLE
Spinal cord analyses should be from C1-T2 

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#116]

**Comment by evaalonsoortiz** [comment]
I will start working on this issue now (expect me to make changes to the notebook). I will post an update when finished.

**Comment by evaalonsoortiz** [comment]
Done via https://github.com/spinal-cord-7t/coil-qc-code/commit/d50eef03b455cc6c3f985845d74d1851c9b25457

<img width="1300" alt="Screenshot 2024-10-25 at 8 19 08 PM" src="https://github.com/user-attachments/assets/f447b423-baf9-4051-8e52-fde38260a173">

<img width="1320" alt="Screenshot 2024-10-25 at 8 19 21 PM" src="https://github.com/user-attachments/assets/68457a10-710e-4fcd-b04a-52fb43d8d29c">
