### ISSUE TITLE
Visually group sites that have the same coil in figures 

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#118]

**Comment by evaalonsoortiz** [comment]
I have assigned a color to each site, with sites having the same coil using different shades of that color.

<img width="1159" alt="Screenshot 2024-10-28 at 4 39 12 PM" src="https://github.com/user-attachments/assets/e7b75984-df0c-4597-84bb-d582c3906305">


<img width="551" alt="Screenshot 2024-10-28 at 4 39 25 PM" src="https://github.com/user-attachments/assets/16d55349-8a2a-4717-b1b5-bc22686ff2ac">
<img width="700" alt="Screenshot 2024-10-28 at 4 39 38 PM" src="https://github.com/user-attachments/assets/932e1aa4-b63e-4801-b3ca-245b153287d0">
<img width="996" alt="Screenshot 2024-10-28 at 4 41 20 PM" src="https://github.com/user-attachments/assets/e0a487c6-fac6-403b-9b49-a371704b990f">
