### ISSUE TITLE
Reduce the dynamic range of the sagittal SNR tiled maps

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#121]

**Comment by evaalonsoortiz** [comment]
I'm doing this on the human script atm.

**Comment by evaalonsoortiz** [comment]
Done via https://github.com/spinal-cord-7t/coil-qc-code/commit/7d1afc4e61bbfb4127e041f84deccb5ec55aff35.

<img width="690" alt="Screenshot 2024-10-25 at 8 29 05 PM" src="https://github.com/user-attachments/assets/1029d82d-85e2-47a9-84e3-9589a891564d">
<img width="698" alt="Screenshot 2024-10-25 at 8 29 16 PM" src="https://github.com/user-attachments/assets/b86e241f-b092-4b08-be51-3cadf0ea313f">


I think that the phantom map dynamic range looks fine, therefore I will now close this issue.
