### ISSUE TITLE
Host processed notebooks with outputs

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#126]
Follow up of #123 

README could contain info about how to run the notebooks, and how to access processed version on gh-pages, eg: https://github.com/spinal-cord-7t/coil-qc-code/blob/gh-pages/ccd8f9a/data_processing-phantom.ipynb

**Comment by jcohenadad** [comment]
Problem of using GH to render the notebook: if too large, it does not render:

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/a472d4ba-2ccf-49c0-af1e-7b600224a694">

Maybe nbviewer works better for large notebooks.

**Comment by jcohenadad** [comment]
nope :-( 

<img width="927" alt="image" src="https://github.com/user-attachments/assets/92002183-6f8a-40e6-95d1-672fc422fd28">

**Comment by jcohenadad** [comment]
Maybe we should convert them into HTML and then host the HTML? @mathieuboudreau any thoughts?

**Comment by jcohenadad** [comment]
Could jupyterlite be a good solution for this?

**Comment by mathieuboudreau** [comment]
Brainstorming/exploring on this this morning, bbl

**Comment by mathieuboudreau** [comment]
@jcohenadad I think the most straightforward way is to take the built notebooks in Actions and then run `jupyter-book build` on them + upload to GHPages via github artifacts. Then the notebooks + run outputs can be viewed as HTMLs built by jupyter book. I've done a small test run in a fork and it worked, will test it now with your full notebooks and report back once those are done. 

https://github.com/mathieuboudreau/coil-qc-code/actions/runs/11578088258

Then, you can point to different gh-pages html pages for each notebooks in your README

**Comment by mathieuboudreau** [comment]
The demo I used is currently built here (using all your pip/sct setup, but a simple plot in the notebook to build it quicker than 40-45 minutes), https://mathieuboudreau.github.io/coil-qc-code/data_processing-human.html, and hopefully this will be replaced in 2 hours with the actual built notebook

**Comment by mathieuboudreau** [comment]
@jcohenadad here's the jupyterbook build (I linked directly to one of the sections near figures): https://mathieuboudreau.github.io/coil-qc-code/executed_notebooks/data_processing-phantom.html#generate-figures . Is this somewhat you had in mind for this issue?

The cell outputs are so verbose that it makes scrolling through the page a bit of a pain; some cell outputs could be hidden for a better user experience. Maybe either by suppressing the output completely or making it collapsable (I think it should be possible but don't know for sure).

**Comment by jcohenadad** [comment]
WOW this is WONDERFUL!!! I'm sold on jupyter book now! Esp. the ability to have a TOC on the right is critical for large stdout. Thank you so much @mathieuboudreau 

Yes, this is exactly what we need! One question though: is it possible to 'easily' go back to previous commits, because that's one of the main desired feature: be able to compare figures across commits

**Comment by mathieuboudreau** [comment]
Instructions to add tags here: https://jupyterbook.org/en/stable/content/metadata.html

**Comment by mathieuboudreau** [comment]
As for your other question, viewing older versions of the built jupyter-book, I don't think this is possible dynamically when using GH-Pages to host, as they only serve the latest one:

https://stackoverflow.com/questions/51548291/can-i-view-changes-to-a-github-hosted-page-before-committing-to-master

However, if you had an AWS S3 bucket setup and would push your built notebooks there during GH Actions with visibility of the HTML and resources set to public in S3, then there would likely be a way to access all prior built pages. You'd just need to ensure to setup a usage threshold in case someone DDOS's your page for any reason, as to not go over the free usage limit

**Comment by mathieuboudreau** [comment]
^ I've never done exactly what I suggested above, there could be additional steps to go from the built notebook -> get it to look like when it's hosted on GH Pages. Maybe @agahkarakuzu would know. I know I've had it host single page Jupyter Books in the past however, as in my old T1 mapping blogposts, eg

https://qmrlab.org/jekyll/2018/10/23/T1-mapping-inversion-recovery.html

they're just an iframe linked to the HTML in an AWS S3 bucket, ie 

https://github.com/qMRLab/qmrlab.github.io/blob/c11d3783be04151bd06cf801636d5478604b50f2/_posts/2018-10-23-T1-mapping-inversion-recovery.md#L40

and 

https://s3.ca-central-1.amazonaws.com/qmrlab-blogs/InversionRecovery.html

And then you could link directly to those past built HTML in your README or wherever

**Comment by jcohenadad** [comment]
> However, if you had an AWS S3 bucket setup and would push your built notebooks there during GH Actions with visibility of the HTML and resources set to public in S3, then there would likely be a way to access all prior built pages. You'd just need to ensure to setup a usage threshold in case someone DDOS's your page for any reason, as to not go over the free usage limit

that is unfortunately too complicated for me, but thank you for looking into it. So unless there is no alternative solution, it looks like i have to abandon the jupyter book approach, and stick to gh-page hosting, making sure the amount of outputs is reduced such that they can be displayed properly

**Comment by jcohenadad** [comment]
> Instructions to add tags here: https://jupyterbook.org/en/stable/content/metadata.html

i'm not sure i understand the benefits of tags vs. headings (the latter being listed on the TOC on the right)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I would try to address this as you did in the workflow, by publishing html outputs on a commit by commit basis as you did in `Copy HTML Notebooks to Commit-Specific Directory`. But I guess it is not working?

**Comment by mathieuboudreau** [comment]
>i'm not sure i understand the benefits of tags vs. headings (the latter being listed on the TOC on the right)

Tags are just to tell Jupyter-Book what to do with that cell; eg do you want to show the code, hide the code, make it collapsible, show the output, hide the output, make it scrollable, etc.

**Comment by mathieuboudreau** [comment]
@jcohenadad the jupyter book build is done for my branch, here's also what it looks like with some of the cell outputs made scrollable: https://spinal-cord-7t.github.io/coil-qc-code/data_processing-phantom.html

The human one didn't generate figures for this run, but I think that's because my notebook had a bug you fixed later this morning in 3488829

**Comment by jcohenadad** [comment]
@mathieuboudreau this is absolutely FANTASTIC!!! Thank you so much! Do you think there is a way to be able to pick a specific commit to display the jupyter book?

**Comment by jcohenadad** [comment]
@mathieuboudreau I'd like to modify the GHA to add special installation of SCT's non-master branch for https://github.com/spinal-cord-7t/coil-qc-code/issues/139, until https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4661 is merged-- OK if I do it?

**Comment by mathieuboudreau** [comment]
>this is absolutely FANTASTIC!!! Thank you so much! Do you think there is a way to be able to pick a specific commit to display the jupyter book?

If you mean that the user could somehow chose different commits/tags/branches like they can do in ReadTheDocs, I don't think so when using GH pages to host it. If somehow the Jupyter Book could be built and hosted by ReadTheDocs, then I think their infrastructure would work with that. I'm not sure if this is possible (jupyter book on rtd), but it maybe? @agahkarakuzu have you ever heard anything like this? They're both using sphinx, maybe it could work somehow?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau it should be possible to use sphinx-book-theme, but not sure how that'd interact with the execution layer. Also JB will move away from sphinx with the next major release, one thing to keep in mind.

**Comment by jcohenadad** [comment]
How about @agahkarakuzu 's suggestion?

>  I would try to address this as you did in the workflow, by publishing html outputs on a commit by commit basis as you did in Copy HTML Notebooks to Commit-Specific Directory. But I guess it is not working?

In my naive mind, I would think of a relatively straightforward solution, wherein the book would be hosted in a subdirectory, eg: something like this: https://spinal-cord-7t.github.io/coil-qc-code/c49a254/README.html

And I guess this means that the folders would keep accumulating here: https://github.com/spinal-cord-7t/coil-qc-code/tree/gh-pages

Which maybe is fine? I dunno...

**Comment by jcohenadad** [comment]
Another option: keep https://spinal-cord-7t.github.io/coil-qc-code/README.html to see the latest built on GH page, but still be able to visualize previous outputs if we run the processed notebook on our local station, after doing a git checkout of the specific commit (as is currently possible to do). @mathieuboudreau would that be an 'easy' option to implement? It seems like this is already possible with your implementation, no?
