### ISSUE TITLE
Is dilation of the spinal cord mask required for metrics extraction?

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#143]
I noticed the mask is dilated by 3 voxels:

https://github.com/spinal-cord-7t/coil-qc-code/blob/a6a8017de62ad80457bc7dbb7bd02033a05160ad/data_processing-human.ipynb#L495-L511

Given that tissue outside the spinal cord can exhibit very different B1+ or B1- values, and that some parts in the vicinity of the cord (eg bony structure from the spine, intervertebral discs) are associated with noisy voxels, I am wondering if dilating doesn't cause more harm than good. @evaalonsoortiz have you evaluated this?

**Comment by evaalonsoortiz** [comment]
I have not, in the sense that I have not compared the signal curves along the cord with/without dilation. But, looking at the B1+/- maps, you are totally correct that at the vicinity of the cord the signal is either noisy (B1+ maps) or drops to zero (B1- in bone). Dropping this would make sense.

**Comment by jcohenadad** [comment]
Comparison before/after dilation:

TFL:
![3de9393e-c767-4fb6-aad5-a01fc759e089](https://github.com/user-attachments/assets/2730150a-4d92-402a-8ac4-b08da6ee2815)

SNR:
![66b19510-9109-45c7-a0c4-2358fe8478f5](https://github.com/user-attachments/assets/161fde08-aeb2-4542-84aa-cc40d1743942)

*: will create the GIF once https://github.com/spinal-cord-7t/coil-qc-code/actions/runs/11636660762 finished running
