### ISSUE TITLE
Unable to upload dataset to OpenNeuro

### ISSUE THREAD

**Issue by Kyota-exe** [spinal-cord-7t/coil-qc-code#15]
OpenNeuro does not accept the dataset as it is, raising errors. Currently, the dataset is stored in [Google Drive](https://drive.google.com/file/d/1PGqqp09sCKfmFE1oewx0m7I2Xdl9eu8e/view?usp=drive_link). 

![IMG_9203](https://github.com/spinal-cord-7t/coil-qc-code/assets/56048818/bc25a9a2-6d3f-4f74-981f-6a024949e689)

Since there seems to be issues in the dataset (#12, #13), we should probably resolve those first before attempting to fix the problems preventing the dataset from being uploaded to OpenNeuro.

**Comment by evaalonsoortiz** [comment]
Is there any additional information about which files are not BIDS compliant?

For issue #12 : As mentioned in the issue (https://github.com/spinal-cord-7t/coil-qc-code/issues/12#issuecomment-1952473648), the notebook should retrieve all 3 DREAM scans and combine them. This means that the DREAM scans with 3 different voltages should be included in the OpenNeuro dataset. However, it doesn't look like the lower and higher voltage scans were converted to BIDS (see my comment here: https://github.com/spinal-cord-7t/coil-qc-code/pull/9#issuecomment-1952548438). This issue should not stop us from making sure that the data we already do have is properly BIDS formatted.

For issue #13 : The correct NYU scans can be sorted out independently of the BIDS conversion issue.

**Comment by Kyota-exe** [comment]
Unfortunately, OpenNeuro doesn't give us much information on what exactly is wrong about the naming. Expanding the error simply enumerates all the files (111 files) and reiterates the error message:
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/56048818/8d4cac23-1cc2-4b20-89c5-7bb2cf1db0d3)

The second error is easily fixable by adding an appropriate `dataset_description.json` file however, which I will do.
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/56048818/6185d39a-2a64-44e5-b978-ff8ac96232df)

**Comment by evaalonsoortiz** [comment]
But we know that the file that is causing the problem is "sub-MGH1_acq-coilQaSagLarge_SNR.nii.gz, yes?

**Comment by evaalonsoortiz** [comment]
Is the suffix "coilQaSagLarge_SNR" part of BIDS?

**Comment by evaalonsoortiz** [comment]
After reading the acq-<label> entry https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#acq, I see that "coilQaSagLarge" is your label, and that "SNR" is a suffix. This must be what is causing the problem. @jcohenadad had pointed out in this comment: https://github.com/spinal-cord-7t/coil-qc-code/pull/9#pullrequestreview-1811994832 that "SNR" is not a BIDS suffix and had advised you on how to proceed in order to decide how to handle this file.

**Comment by Kyota-exe** [comment]
> But we know that the file that is causing the problem is "sub-MGH1_acq-coilQaSagLarge_SNR.nii.gz, yes?

This is just the first file for which this error applies, there are in total 111 files that have filenames that don't comply with the BIDS convention (according to OpenNeuro at least).

**Comment by Kyota-exe** [comment]
I have created a [new topic on NeuroStars](https://neurostars.org/t/feedback-on-bids-suffixes/28479) asking for feedback and listing the scans for which the filenames are detected as incorrect on OpenNeuro.

**Comment by Kyota-exe** [comment]
Closing this issue as I no longer have any problems uploading the dataset on OpenNeuro.
