### ISSUE TITLE
Missing comments about subject removal

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#20]
The following code lacks documentation-- why are there two cells doing the same thing? why removing subject 4?

https://github.com/spinal-cord-7t/coil-qc-code/blob/f9fcb557bc52a6afb02e99a15da0444d90376ee0/data_processing.ipynb#L91-L114

**Comment by Kyota-exe** [comment]
I initially added this cell because I was not sure what to do about the analysis of SpinozaV6, which does not have any MP2RAGE scans, and for which segmentation is thus not possible. I can correct this if the intention for the analysis of the phantom subject SpinozaV6 can be clarified for me. Should we perform segmentation using a different scan, for instance?

**Comment by jcohenadad** [comment]
I would simply not include SpinozaV6 in the same dataset as the human dataset. I would create another dataset and also upload it on OpenNeuro. 

BTW: the [2.0.1 dataset](https://openneuro.org/datasets/ds005025/versions/2.0.1) does _not_ include SpinozaV6, hence the code does not require this cell to work.

**Comment by jcohenadad** [comment]
> Could you clarify what you mean by this? SpinozaV6 is sub4, and every site in v2.0.1 on OpenNeuro includes sub4. 

I had no idea sub4 was spinoza, because it is written nowhere in the README (the README is empty), and the description.tsv file says what sub4 is "homo sapiens":

![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/712023bf-9208-4fae-89ce-b8b39454fcfd)

So, two options:
- the README and description.tsv is fixed
- the spinoza data is uploaded to another dataset

the latter is "cleaner" from a data analysis standpoint (because no need for an "if case") and data curation standpoint (more homogeneous, which is what we expected from a BIDS dataset).
