### ISSUE TITLE
MP2RAGE data missing

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#26]
The following files are missing from the dataset v2.0.1:
- `sub-MGH4_UNIT1.nii.gz`
- `sub-MNI4_UNIT1.nii.gz`
- `sub-MPI4_UNIT1.nii.gz`
- `sub-Marseille4_UNIT1.nii.gz`
- `sub-NTNU4_UNIT1.nii.gz`
- `sub-NYU4_UNIT1.nii.gz`
- `sub-UCL4_UNIT1.nii.gz`

Do we have more explanations about why these images are missing? Interestingly it only concerns the fourth subject. It should be documented in the dataset's README.

**Comment by Kyota-exe** [comment]
I'm sorry if this is obvious, but note that the fourth subject is SpinozaV6, so MP2RAGE scans were not acquired for the phantom subject.

**Comment by jcohenadad** [comment]
> I'm sorry if this is obvious, but note that the fourth subject is SpinozaV6, so MP2RAGE scans were not acquired for the phantom subject.

not obvious-- see https://github.com/spinal-cord-7t/coil-qc-code/issues/20#issuecomment-2057883222

**Comment by jcohenadad** [comment]
Explanation given in https://github.com/spinal-cord-7t/coil-qc-code/issues/26#issuecomment-2057546484 solves the issue-- another (related) issue: #83
