### ISSUE TITLE
Generate manual disc labels

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#27]
Write up a procedure with [manual-correction](https://github.com/spinalcordtoolbox/manual-correction) to generate the disc labels.

Related to #23 

1. Install https://github.com/spinalcordtoolbox/manual-correction
2. Download and unzip this config file: [config_labels.yml.zip](https://github.com/spinal-cord-7t/coil-qc-code/files/14971935/config_labels.yml.zip)
3. Run (adapt path):
   ```console
   python ~/code/manual-correction/manual_correction.py -path-img data -path-out data/derivatives/labels -config config_labels.yml
   ```

This generated the following derivatives [labels.zip](https://github.com/spinal-cord-7t/coil-qc-code/files/14971939/labels.zip), which need to be placed under the `derivatives/` folder of the input data for subsequent analysis.

TODO: 
- [x] Complete the manual disc labeling for other subjects (here, as an example, I only selected the first subject per site).
- [x] Upload to OpenNeuro (1/2): https://openneuro.org/datasets/ds005025/versions/2.3.0

@NathanMolinier: tagging you so you are aware of another dataset (MP2RAGE UNI) with disc labels

**Comment by evaalonsoortiz** [comment]
The code no longer runs vertebral labeling, was the removal of that intentional?

**Comment by jcohenadad** [comment]
> The code no longer runs vertebral labeling, was the removal of that intentional?

yes, motivated by https://github.com/spinal-cord-7t/coil-qc-code/issues/23

**Comment by jcohenadad** [comment]
Second round of labels, using this YAML: [config_labels 2.yml.zip](https://github.com/spinal-cord-7t/coil-qc-code/files/15081524/config_labels.2.yml.zip)

**Comment by jcohenadad** [comment]
Fixed in https://openneuro.org/datasets/ds005025/versions/2.3.1
