### ISSUE TITLE
Subject ID should be coherently referred to across the dataset

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#31]
Currently, our list mixes center name (eg: `MGH`, `NYU`) and city (eg: `Marseille`).

We should use a single convention. 

My suggestion, given that Marseille is the only 'outlier', would be to use center name. In this case, we should replace `Marseille` by `CRMBM`

**Comment by Kyota-exe** [comment]
According to [this comment from #13](https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1952850690), we would also have to replace NYU by MtSinai.

**Comment by jcohenadad** [comment]
> According to https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1952850690, we would also have to replace NYU by MtSinai.

Correct. And to be consistent with the use of acronym, we could also consider calling the dataset MSSM (Mount Sinai School of Medicine). Would that be acceptable to you @alanseifert ?

**Comment by Kyota-exe** [comment]
I created a new version, v2.1.0, on OpenNeuro, implementing the following changes:
NYU -> MSSM
Marseille -> CRMBM

This issue should thus now be solved.

**Comment by jcohenadad** [comment]
Nice job @Kyota-exe 👏
