### ISSUE TITLE
Phantom data is mixed with human data with poor documentation

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#38]
I had no idea sub4 was spinoza, because it is written nowhere in the README (the README is empty), and the description.tsv file says what sub4 is "homo sapiens":

![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/712023bf-9208-4fae-89ce-b8b39454fcfd)

So, two options:
- the README and description.tsv is fixed
- the spinoza data is uploaded to another dataset

The latter is "cleaner" from a data analysis standpoint (because no need for an "if case") and data curation standpoint (more homogeneous, which is what we expected from a BIDS dataset). 

Additional context: 
- https://github.com/spinal-cord-7t/coil-qc-code/issues/26#issuecomment-2057883541
- https://github.com/spinal-cord-7t/coil-qc-code/issues/20#issuecomment-2057883222

**Comment by Kyota-exe** [comment]
@jcohenadad Do you think we can move forward with moving the Spinoza data to another dataset? For all it's worth, I agree that this would be the cleaner solution.

**Comment by jcohenadad** [comment]
> @jcohenadad Do you think we can move forward with moving the Spinoza data to another dataset? For all it's worth, I agree that this would be the cleaner solution.

@evaalonsoortiz is leading this project and should have the final word

**Comment by evaalonsoortiz** [comment]
Is the proposal to separate the datasets but keep the same data analysis script? The data analysis is not the same for human and phantom data (maybe 40% of it is common to both). If we separate the datasets, then I think I'll separate the scripts as well.

**Comment by jcohenadad** [comment]
the script would indeed need to be separate

**Comment by evaalonsoortiz** [comment]
Ok @Kyota-exe let's go ahead and separate both the datasets and scripts

**Comment by Kyota-exe** [comment]
I have removed the phantom scans from ds005025 (new version v2.2.0) and moved them to ds00509. @jcohenadad and @evaalonsoortiz have been added as admins to the new phantom database.

**Comment by evaalonsoortiz** [comment]
We now have 2 separate data repos and 2 separate analysis scripts, therefore I will close this issue.
