### ISSUE TITLE
Remove dropping phantom once new data uploaded

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#39]
If we end up dropping the phantom data from the in vivo data (https://github.com/spinal-cord-7t/coil-qc-code/issues/38), we should remove that code:

https://github.com/spinal-cord-7t/coil-qc-code/blob/20dd31a5f37ee9d638e52a997d6c9b390afe4998/data_processing.ipynb#L75-L76

**Comment by Kyota-exe** [comment]
This issue should be resolved by b8cb381.

**Comment by jcohenadad** [comment]
todo before closing https://github.com/spinal-cord-7t/coil-qc-code/commit/b8cb3813c361c95951f19abaef6a976ddb537d25#r141269752
