### ISSUE TITLE
CHANGE file does not list 2.1.0

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#40]
After #31, 2.1.0 was published but the CHANGE file was not adequately updated:

![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/cb1f8056-9471-4a1d-b7a4-4174b0417b1b)

**Comment by Kyota-exe** [comment]
Weirdly enough, the CHANGE file is actually correctly updated in v2.1.0, but not in the draft. Maybe I accidently reverted the CHANGES file in the draft to an older version?
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/56048818/d63ef826-76f8-45eb-acba-2ccf4a842a64)

**Comment by jcohenadad** [comment]
Weird indeed... do you want to inform the OpenNeuro team? Or maybe let's wait a day for things to sync.

**Comment by Kyota-exe** [comment]
I attempted to update the CHANGES file by re-uploading the correct one in the draft version, but that doesn't seem to work either; the CHANGES file stubbornly stays outdated.

> Weird indeed... do you want to inform the OpenNeuro team? Or maybe let's wait a day for things to sync.

I agree, I will revisit this issue tomorrow.

**Comment by Kyota-exe** [comment]
This issue has still not been resolved. It is however not a huge issue as snapshot versions produce the correct CHANGES file; only the CHANGES file from the draft version is affected by this bug. Still, it may be a good idea to inform the OpenNeuro team as suggested by @jcohenadad so they are aware of this issue.

**Comment by Kyota-exe** [comment]
Given that this issue has not resolved itself after 2 weeks, I have created a support ticket on OpenNeuro.

**Comment by Kyota-exe** [comment]
I was notified by Chris from the OpenNeuro team that they'll look into the issue on May 8, and expected to receive a follow-up email, but didn't. The issue seems to have resolved itself, however. I will thus close this issue since it has been resolved.
