### ISSUE TITLE
Make human data public?

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#42]
Can we make the OpenNeuro repositories public @evaalonsoortiz @Kyota-exe ?

This is a requirement for someone external (eg reviewer) to be able to test the analysis pipeline.

**Comment by Kyota-exe** [comment]
I don't think this is a good idea, as there are still some issues to be dealt with first (e.g., #37) and because we should probably deface the scans before making them public. I am looking into this this weekend.

**Comment by jcohenadad** [comment]
Is there any update on this @evaalonsoortiz ? I just realized that ds005025 is still not public on OpenNeuro, hence our results are currently not replicable (see https://github.com/spinal-cord-7t/coil-qc-code/issues/123#issuecomment-2440037749). 

![image](https://github.com/user-attachments/assets/6d2f8ef9-6a50-471d-b244-ee3de49e245b)

**Comment by jcohenadad** [comment]
Ah! Looks like the phantom data is still not public either:

![image](https://github.com/user-attachments/assets/86d3feea-b858-4c95-a757-1cd76c14bdc0)

Surely we can make this one public at least-- I'll do it now so I can continue working on https://github.com/spinal-cord-7t/coil-qc-code/issues/123#issuecomment-2440037749

**Comment by jcohenadad** [comment]
ok, the phantom data is now public: https://openneuro.org/datasets/ds005090/versions/1.1.0

**Comment by jcohenadad** [comment]
Human data are now public, closing
