### ISSUE TITLE
`sub-MPI2_inv-1_part-mag_MP2RAGE.nii.gz` is missing

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#48]
This image is missing from https://doi.org/10.18112/openneuro.ds005025.v2.2.0

We need it for #47

Any reason for this? @evaalonsoortiz @Kyota-exe

**Comment by Kyota-exe** [comment]
Only the UNI images MP2RAGE scan was acquired for subject2 of MPI. This is the case for CRMBM as well. I asked @evaalonsoortiz about this in the past, and she said that it was fine because we only use the UNI images scan for the analysis, but now that this is no longer the case, I'm not sure what the original reason is for why they are missing.

**Comment by evaalonsoortiz** [comment]
I'll reach out to our contacts at MPI and CRMBM to see if we can get the sub-xxx_inv-1_part-mag_MP2RAGE.nii.gz scans.

**Comment by Kyota-exe** [comment]
Yes, subject2 for both sites, which corresponds to L.

I’m not sure we still need them for the analysis, however; @jcohenadad has already resolved #47 with a manual segmentation for sub-MPI2.

**Comment by jcohenadad** [comment]
> I'll reach out to our contacts at MPI and CRMBM to see if we can get the sub-xxx_inv-1_part-mag_MP2RAGE.nii.gz scans.

I would also ask for inv-2 (just in case...)

> I’m not sure we still need them for the analysis, however; @jcohenadad has already resolved https://github.com/spinal-cord-7t/coil-qc-code/issues/47 with a manual segmentation for sub-MPI2.

Better to be exhaustive and consistent across subjects, regardless the analysis pipeline

**Comment by evaalonsoortiz** [comment]
Emails have been sent, I'll share the data with @Kyota-exe when I get them.

**Comment by Kyota-exe** [comment]
The INV1 and INV2 scans for CRMBM have been uploaded to the dataset: https://openneuro.org/datasets/ds005025

**Comment by evaalonsoortiz** [comment]
Update: inv-1 and inv-2 scans for sub-MPI2 have been added to our internal servers and sent to @Kyota-exe for uploading to openneuro

**Comment by Kyota-exe** [comment]
The MP2RAGE INV1 and INV2 scans for sub-MPI2 have been uploaded to OpenNeuro in v2.4.0. 
This issue should now be resolved.
