### ISSUE TITLE
Do not upload generated images alongside the notebook

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#5]
The notebook is saved with the outputs, which adds binary data on GH:
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/f66df5a8-d134-460a-a926-1eb65d48173e)

It is generally recommended to not save the outputs, for more efficient version control (and not add unnecessary binaries to the git history)

More details at: https://discourse.jupyter.org/t/how-to-version-jupyter-notebooks-in-git-without-output/10748

**Comment by jcohenadad** [comment]
In fact, editing the code on GitHub doesn't even work:
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/f6425b02-9c05-4f8a-9498-70ec5c622c99)

Making it extremely difficult to comment, add suggestions, etc.

I suggest to remove that file, and upload another one without the outputs. I also suggest changing the name for something more generic (ie without Kyota's name) and without space for UNIX compatibility, eg: `THS_CoilQA_code.ipynb`

**Comment by Kyota-exe** [comment]
5a9b793 solves this. 

I haven’t found any way to upload the notebook without outputs without first clearing all the outputs from Google Colab first, which makes it slightly inconvenient, because it means you have to rerun the notebook for the outputs after pushing to GitHub, which usually takes a while. I don’t think there’s a way around this though.

**Comment by jcohenadad** [comment]
Fixed by https://github.com/spinal-cord-7t/coil-qc-code/commit/5a9b7939122e2ebdb6911e7e7badd165b94bdfc6

**Comment by jcohenadad** [comment]
Reopening this issue because binaries and notebook outputs were again pushed to the main branch in https://github.com/spinal-cord-7t/coil-qc-code/pull/11

**Comment by Kyota-exe** [comment]
Closing as this was resolved for #11 by @evaalonsoortiz.
