### ISSUE TITLE
Integrate Jupyter notebook with GitHub for easy review

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#6]
Maybe the feature is already integrated by default?

More details at: https://blog.reviewnb.com/how-to-add-comments-to-notebook-diffs-github/

**Comment by Kyota-exe** [comment]
Hello Dr. Cohen-Adad, thank you for the access. To push notebook changes from Google Colab to GitHub, I am using the GitHub integration in Google Colab, which allows me to "Save a copy to GitHub". This uploads the notebook to this repository with a "Open in Colab" badge. Even after clearing outputs before pushing a commit (5a9b793) however, it is still impossible to comment on specific cells in the notebook code in GitHub. The GitHub integration for Google Colab is thus limited.

The article you linked mentions [ReviewNB](reviewnb.com) as being a way we can comment on specific notebook cells. I tried it and it works, but you have to write the comments on their website, and they are not accessible from the GitHub interface. [Here is the link for the ReviewNB for this repository](https://app.reviewnb.com/spinal-cord-7t/coil-qc-code/blob/main/THS_CoilQA_code.ipynb/) and [this is the comment I made on ReviewNB to test it](https://app.reviewnb.com/spinal-cord-7t/coil-qc-code/blob/main/THS_CoilQA_code.ipynb/file/#comment-nb-bcf74cc4).

Should we use ReviewNB for commenting on the notebook code? It seems to be the most straightforward way to make comments on specific notebook cells, but having to use a new website just for the comments is a bit annoying. Personally, I think being able to write comments on the commit (and not on a specific notebook cell) is enough for the notebook code.

**Comment by jcohenadad** [comment]
agreed, let’s stick to comments on github’s commits

**Comment by evaalonsoortiz** [comment]
@jcohenadad I will close this issue unless you object.
