### ISSUE TITLE
Phantom dataset json files have incorrect format/information

### ISSUE THREAD

**Issue by evaalonsoortiz** [spinal-cord-7t/coil-qc-code#60]
The phantom dataset (https://openneuro.org/datasets/ds005090/download) .json files appear to be incorrectly formatted

<img width="819" alt="Screen Shot 2024-05-01 at 10 59 35 AM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/e212b571-fe81-484e-a938-b30e84c64c2e">

**Comment by Kyota-exe** [comment]
I believe that may be a downloading issue? I encounter no problems getting the correctly formatted json files, and the view on the OpenNeuro website does not display any problems: https://openneuro.org/datasets/ds005090/file-display/sub-CRMBM:fmap:sub-CRMBM_acq-famp-1.5_TB1DREAM.json

**Comment by evaalonsoortiz** [comment]
Huh, you're right. I downloaded, the files are fine.
