### ISSUE TITLE
Consider cropping the g-factor map

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#62]
In some articles, g-factor maps are cropped. Eg from May et al (showing similar coil):

<img width="805" alt="image" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/0565acc9-ea20-4f4f-a874-6598c0d0f17b">

**Comment by evaalonsoortiz** [comment]
I don't think I agree. The 2x2 g-factor maps we show don't really have a region with no "structure" that we could crop out. 

Ex:

phantom
<img width="778" alt="Screenshot 2024-05-31 at 12 08 41 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/1e26f213-0973-4d8d-ab69-644cc0c8b584">

In-vivo
<img width="793" alt="Screenshot 2024-05-31 at 12 08 56 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/a7696dc6-48ae-4556-939c-270fea8af109">

If one of you have a proposed crop for these images, please show me what you mean by quickly screen capping the region you would keep for one example image.

**Comment by jcohenadad** [comment]
I agree that the gfactor maps shown in https://github.com/spinal-cord-7t/coil-qc-code/issues/62#issuecomment-2142573773 should not be cropped-- they are OK as is.

I'm not sure what images I was referring to in my original comment https://github.com/spinal-cord-7t/coil-qc-code/issues/62#issue-2288955849-- i should have added a screenshot-- my mistake
