### ISSUE TITLE
RuntimeError: ../../sub-CRMBM/fmap/mask_spinalcord_DREAM.nii.gz does not exist

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#79]
Using version d1f8ea06cf20d9a39a57982a72735bcd9136dea2

Indeed, masks for DREAM and SNR used in the code below are not created before:

https://github.com/spinal-cord-7t/coil-qc-code/blob/83dfd087445fb045dad77d2320847ff4af5492f9/data_processing-phantom.ipynb#L401-L402

**Comment by jcohenadad** [comment]
Two options:
- register the DREAM and SNR to the TFL
- create separate ROIs
  - cons: introduces a bias when comparing TFL vs. DREAM (ie: we should be comparing using the same mask)

**Comment by evaalonsoortiz** [comment]
I had already co-registered the TFL spinal cord mask to the DREAM and SNR spaces via the command line, and I must have forgotten to add the line of code to the notebook. This way you use the same mask, but don't have the different coverage problem. 

Unfortunately, I don't remember the exact line of code that I used, but this seems to have reproduced the masks I had:
https://github.com/spinal-cord-7t/coil-qc-code/blob/d2bc792c5388e0d31b4008ca177741a2d7a0f590/data_processing-phantom.ipynb#L359-L364

**Comment by jcohenadad** [comment]
Change implemented in https://github.com/spinal-cord-7t/coil-qc-code/commit/d2bc792c5388e0d31b4008ca177741a2d7a0f590
