### ISSUE TITLE
Why redefining the labels for DREAM and SNR is they already exist for TFL?

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#87]
https://github.com/spinal-cord-7t/coil-qc-code/blob/da016b61566d5e8f4a00d700e82a921bed167e25/data_processing-phantom.ipynb#L316-L344

Assuming the phantom was not moved between the acquisition of the TFL, DREAM and SNR, there is no need to redefine the labels, given that using the qform we can put the label from the TFL space into the space of the DREAM and SNR space.

We should simplify the code and use only one set of pre-defined labels from one single contrast, unless there was another reason for creating labels for the DREAM and SNR images @evaalonsoortiz ?

Related to #81 #82

**Comment by evaalonsoortiz** [comment]
No other reason other than I had not thought of that/haven't done it before.

**Comment by jcohenadad** [comment]
While working on using TFL labels only, I noticed that for some sites, eg NTNU, the qform-based registration is bad:

![ezgif-4-f426dc34df](https://github.com/spinal-cord-7t/coil-qc-code/assets/2482071/3409a1ff-b1a3-42d7-a05f-198c99b730cd)
